//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class info
    {
        public int custoumer_id { get; set; }
        public string custoumer_Name { get; set; }
        public Nullable<int> Age { get; set; }
        public Nullable<int> city { get; set; }
        public Nullable<int> phone { get; set; }
        public string email { get; set; }
        public string photo { get; set; }
    
        public virtual city city1 { get; set; }
    }
}
